//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OZGECMISIM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CVdbEntities : DbContext
    {
        public CVdbEntities()
            : base("name=CVdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRES> ADRES { get; set; }
        public virtual DbSet<CALISMALARIM> CALISMALARIM { get; set; }
        public virtual DbSet<Hakkimda> Hakkimda { get; set; }
        public virtual DbSet<ILETISIM> ILETISIM { get; set; }
        public virtual DbSet<YETENEKLERIM> YETENEKLERIM { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
    }
}
